[#1] Creating task listing UI
JhumurChatterjee/wheel pull request #4
Opened 2021-05-19 15:55 UTC by JhumurChatterjee

2021-05-25 05:50 UTC, kabir4691 commented
@JhumurChatterjee Please fix the PR details according to our discussion.

2021-05-25 06:41 UTC, JhumurChatterjee commented
@kabir4691 I have changed the PR details. Please have a look.

2021-05-25 08:12 UTC, kabir4691 commented
@JhumurChatterjee Good job.

2021-05-25 08:13 UTC, kabir4691 commented
@karthiknmenon Please review her code.

2021-05-25 08:48 UTC, karthiknmenon requested changes
@JhumurChatterjee Please check the suggestions.

2021-05-25 08:48 UTC, karthiknmenon commented on app/javascript/src/components/Dashboard/Contacts/ContactTable.jsx
> +            <th className="text-center">Add to Basecamp</th>
Please create an empty `<th></th>` here. 
This will be corresponding to the two IconButtons that we have from Delete and Edit actions.

2021-05-25 08:48 UTC, karthiknmenon commented on app/javascript/src/components/Dashboard/Contacts/ContactTable.jsx
> +      <table className="nui-table nui-table--checkbox">
Please add classnames `nui-table--hover nui-table--actions` too.

2021-05-25 08:48 UTC, karthiknmenon commented on app/javascript/src/components/Dashboard/Contacts/ContactTable.jsx
> +                </Tooltip>
Wrap them inside a single `<td></td>`. This will correspond to the empty `th` created earlier.

2021-05-25 08:48 UTC, karthiknmenon commented on app/javascript/src/components/Dashboard/Contacts/index.jsx
> +
Please remove this extra space.

2021-05-25 08:48 UTC, karthiknmenon commented on app/javascript/src/components/Dashboard/Notes/NewNoteForm.jsx
> +              { label: "Bug", value: "bug" },
You could move constants like these to a separate file called `constants.js`

2021-05-25 08:48 UTC, karthiknmenon commented on app/javascript/src/components/Dashboard/Notes/NoteTable.jsx
> +import moment from "moment";
Please use `dayjs` over `moment`.

2021-05-25 08:48 UTC, karthiknmenon commented on app/javascript/src/components/Dashboard/Notes/NoteTable.jsx
> +            <th className="text-center">Contact</th>
Create an empty `th` corresponding to the Icon ActionButton

2021-05-25 08:48 UTC, karthiknmenon commented on app/javascript/src/components/Dashboard/Notes/NoteTable.jsx
>        <table className="nui-table nui-table--checkbox">
Please add classnames `nui-table--hover nui-table--actions` too.

2021-05-25 08:48 UTC, karthiknmenon commented on app/javascript/src/components/Dashboard/Notes/NoteTable.jsx
> +                  <a href="#">{note.title}</a>
Please use neetoUI Button with `style="link"`.
Refer the documentation [here](https://neeto-ui.netlify.app/#/button)

2021-05-25 08:48 UTC, karthiknmenon commented on app/javascript/src/components/Dashboard/Notes/NoteTable.jsx
> +              </td>
Wrap these two IconButtons inside a single `td`

2021-05-25 15:09 UTC, JhumurChatterjee commented
@karthiknmenon I have fixed the comments. Please have a look.

2021-05-25 18:15 UTC, karthiknmenon requested changes
@JhumurChatterjee Just one small change. The rest of the changes looks good.

2021-05-25 18:15 UTC, karthiknmenon commented on app/javascript/src/components/Dashboard/Notes/NewNoteForm.jsx
> +import contactsApi from "apis/contacts";
Please sort the import statements as required.

2021-05-26 06:11 UTC, JhumurChatterjee commented
@karthiknmenon I have fixed comment. Please have a look.

2021-05-26 15:59 UTC, karthiknmenon requested changes
@JhumurChatterjee 
Please check the suggestion. 
Please read [Sorting import statements](https://bigbinary.com/react-best-practices/sort-import-statements#sorting-import-statements) as a reference.

2021-05-26 15:59 UTC, karthiknmenon commented on app/javascript/src/components/Dashboard/Contacts/index.jsx
> +import contactsApi from "apis/contacts";
@JhumurChatterjee 
Please place aliased/package imports at the top and relative imports at the bottom

2021-05-26 17:13 UTC, karthiknmenon commented
LGTM. 🚀

2021-05-26 17:13 UTC, merged